### ISSUE TITLE
Sometimes the player.name is 'null'

### ISSUE THREAD

**Issue by chrisl8** [doby162/witchazzan-server#5]
Sometimes the player data coming into the client from the server lists the names of all players as "null", or at least that is how it is interpreted by the JavaScript JSON.parse.

I'm not sure if this a bug in the random name generator, or something else.

It may not be worth fixing, if we are going to make player IDs, but for now it requires me restarting the server to fix it when it happens, because it stays that way until the server is restarted.

**Comment by doby162** [comment]
Now that players have a unique ID, all players are named unknown human until they log in. Eventually logging in will be mandatory
